# Generated by Django 5.2 on 2025-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessible_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
